site_name: cml
site_description: A simple command line tool for running Coupled Map Lattice simualtions.
site_author: Michael May
site_url: https://michaelmay.github.io/cml
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: quick_start.md
  - User Guide:
      - Overview: overview.md
      - Examples: examples.md
  - Contributing: contributing.md
